### ISSUE TITLE
when does this repo finish?

### ISSUE THREAD

**Issue by TooTouch** [KimJaehee0725/BiEncoder-Experiments#1]
I'm waiting the results.
Please let me know when you finish.

Best regards,

**Comment by KimJaehee0725** [comment]
This project will be maintained continuously for personal research purpose. 

If you want any implementation for bi-encoder structure training strategy, let me know anytime. 

It will helps me a lot and maybe for you. 

Appreciate your attention for this little project. 

Best regards.
